Sqlstore update
yourhe/stores pull request #2
Opened 2019-03-13 09:44 UTC by lawwy

1.修改sql Create方法，将自增的id赋给传入的结构体

2019-03-14 05:54 UTC, yourhe requested changes

2019-03-14 05:54 UTC, yourhe commented on sql2/sql.go
>  		if name != s.pk {
s.pk 是用来判断是否主键？

如果是的话这里建议变成方法

func (s *xxx)isPK(key) bool {
  return key == s.pk
}

if i!sPK(name) {
......
} else {
.....
}

2019-03-14 05:54 UTC, yourhe commented on sql2/sql.go
>  func (s *SqlBackend) Update(id int64, model interface{}) error {
update :117 开始这部分反射的代码，与create 的reflect代码是否有合并的可能？

2019-03-14 05:54 UTC, yourhe commented on sql2/sql.go
> +	ff := TypeFields(t)
TypeFields 这个名称范围太大。 好的代码在不添加注释的情况下，这个方法名称应该可以代替注释。
使他人无需猜测其功能含义
// Extract Fields Names With Type
ExtractFieldsNames？
GetFieldNames？
方法名称的定义，最好的准则就是。能够最大限度代替注释。 另其他人阅读时更轻松

2019-03-14 05:54 UTC, yourhe commented on sql2/sql.go
> +	ff = StringFilter(ff, func(f string) bool {
StringFilter 问题同上
按原用的代码 if name != s.pk, 其实一个辨识度高的方法名是否更合理？
例如  if !IsPK()

2019-03-14 05:54 UTC, yourhe commented on sql2/sql.go
> +	query := InsertSQL(s.table, StringMap(ff, strings.ToLower))
StringMap ? 这个方法名称的定义，和实际上实现的功能貌似没什么关联性
特别是Map误导，没看到任何与Map有关的功能存在

2019-03-14 05:54 UTC, yourhe commented on sql2/sql.go
> +	query := InsertSQL(s.table, StringMap(ff, strings.ToLower))
InsertSQL 建议改名为 BuildInserSQL， 这类更能描述你的方法意图的名称

2019-03-14 05:54 UTC, yourhe commented on sql2/sql.go
>  	t := reflect.TypeOf(model).Elem()
变量 t ，v 是否可以想一个更有价值的名称，方便以后阅读
例如 ：t => elemType ?

2019-03-18 00:46 UTC, lawwy commented on sql2/sql.go
>  func (s *SqlBackend) Update(id int64, model interface{}) error {
有这样的可能，因为代码很像，考虑到保持方法的单一，个人认为可以暂不合并

2019-03-25 05:37 UTC, merged